from talon import Module
from .core.game_core import move_dir, step_dir, move_dir_toggle, stopper, game_click, mouse_calibrate_90_y, mouse_calibrate_x_360, mouse_reset_center_y
from ..mouse_move_adv.mouse_move_adv import mouse_move_degrees, mouse_move_continuous, mouse_move_continuous_stop

mod = Module()

action_duration_ms = 200

@mod.action_class
class Actions:
    def game_click(button: int = 0, hold: int = 16000): """Left click"""; game_click(button, hold)
    def game_move_dir_hold_a(): """Start holding direction 'a'"""; move_dir('a')
    def game_move_dir_hold_d(): """Start holding direction 'd'"""; move_dir('d')
    def game_move_dir_hold_w(): """Start holding direction 'w'"""; move_dir('w')
    def game_move_dir_hold_s(): """Start holding direction 's'"""; move_dir('s')
    def game_move_dir_toggle_a(): """Toggle between stop and holding direction 'a'"""; move_dir_toggle('a')
    def game_move_dir_toggle_d(): """Toggle between stop and holding direction 'd'"""; move_dir_toggle('d')
    def game_move_dir_toggle_w(): """Toggle between stop and holding direction 'w'"""; move_dir_toggle('w')
    def game_move_dir_toggle_s(): """Toggle between stop and holding direction 's'"""; move_dir_toggle('s')
    def game_move_dir_step_a(): """Briefly hold direction 'a'"""; step_dir('a', '200ms')
    def game_move_dir_step_d(): """Briefly hold direction 'd'"""; step_dir('d', '200ms')
    def game_move_dir_step_w(): """Briefly hold direction 'w'"""; step_dir('w', '200ms')
    def game_move_dir_step_s(): """Briefly hold direction 's'"""; step_dir('s', '200ms')
    def game_stopper(): """All purpose stopper for movement and mouse"""; stopper()
    def game_stop_all(): """Stop all movement and mouse actions"""; stopper()
    def game_turn_left_15(): """Turn left 15 degrees"""; mouse_move_degrees(-15, 0, action_duration_ms)
    def game_turn_left_30(): """Turn left 30 degrees"""; mouse_move_degrees(-30, 0, action_duration_ms)
    def game_turn_left_45(): """Turn left 45 degrees"""; mouse_move_degrees(-45, 0, action_duration_ms)
    def game_turn_left_60(): """Turn left 60 degrees"""; mouse_move_degrees(-60, 0, action_duration_ms)
    def game_turn_left_75(): """Turn left 75 degrees"""; mouse_move_degrees(-75, 0, action_duration_ms)
    def game_turn_left_90(): """Turn left 90 degrees"""; mouse_move_degrees(-90, 0, action_duration_ms)
    def game_turn_left(deg: int): """Turn left x degrees"""; mouse_move_degrees(-deg, 0 , action_duration_ms)
    def game_turn_right_15(): """Turn right 15 degrees"""; mouse_move_degrees(15, 0, action_duration_ms)
    def game_turn_right_30(): """Turn right 30 degrees"""; mouse_move_degrees(30, 0, action_duration_ms)
    def game_turn_right_45(): """Turn right 45 degrees"""; mouse_move_degrees(45, 0, action_duration_ms)
    def game_turn_right_60(): """Turn right 60 degrees"""; mouse_move_degrees(60, 0, action_duration_ms)
    def game_turn_right_75(): """Turn right 75 degrees"""; mouse_move_degrees(75, 0, action_duration_ms)
    def game_turn_right_90(): """Turn right 90 degrees"""; mouse_move_degrees(90, 0, action_duration_ms)
    def game_turn_right(deg: int): """Turn right x degrees"""; mouse_move_degrees(deg, 0 , action_duration_ms)
    def game_turn_right_continuous(speed: int): """Turn right continuously at speed x"""; mouse_move_continuous(1, 0, speed)
    def game_turn_right_continuous_5(): """Turn right continuously speed 5"""; mouse_move_continuous(1, 0, 5)
    def game_turn_right_continuous_10(): """Turn right continuously speed 10"""; mouse_move_continuous(1, 0, 10)
    def game_turn_right_continuous_20(): """Turn right continuously speed 20"""; mouse_move_continuous(1, 0, 20)
    def game_turn_right_continuous_30(): """Turn right continuously speed 30"""; mouse_move_continuous(1, 0, 30)
    def game_turn_right_continuous_50(): """Turn right continuously speed 50"""; mouse_move_continuous(1, 0, 50)
    def game_turn_right_continuous_100(): """Turn right continuously speed 100"""; mouse_move_continuous(1, 0, 100)
    def game_turn_left_continuous(speed: int): """Turn left continuously at speed x"""; mouse_move_continuous(-1, 0, speed)
    def game_turn_left_continuous_5(): """Turn left continuously speed 5"""; mouse_move_continuous(-1, 0, 5)
    def game_turn_left_continuous_10(): """Turn left continuously speed 10"""; mouse_move_continuous(-1, 0, 10)
    def game_turn_left_continuous_20(): """Turn left continuously speed 20"""; mouse_move_continuous(-1, 0, 20)
    def game_turn_left_continuous_30(): """Turn left continuously speed 30"""; mouse_move_continuous(-1, 0, 30)
    def game_turn_left_continuous_50(): """Turn left continuously speed 50"""; mouse_move_continuous(-1, 0, 50)
    def game_turn_left_continuous_100(): """Turn left continuously speed 100"""; mouse_move_continuous(-1, 0, 100)
    def game_look_up_continuous(speed: int): """Look up continuously at speed x"""; mouse_move_continuous(0, -1, speed)
    def game_look_up_continuous_5(): """Look up continuously speed 5"""; mouse_move_continuous(0, -1, 5)
    def game_look_up_continuous_10(): """Look up continuously speed 10"""; mouse_move_continuous(0, -1, 10)
    def game_look_up_continuous_20(): """Look up continuously speed 20"""; mouse_move_continuous(0, -1, 20)
    def game_look_up_continuous_30(): """Look up continuously speed 30"""; mouse_move_continuous(0, -1, 30)
    def game_look_up_continuous_50(): """Look up continuously speed 50"""; mouse_move_continuous(0, -1, 50)
    def game_look_up_continuous_100(): """Look up continuously speed 100"""; mouse_move_continuous(0, -1, 100)
    def game_look_down_continuous(speed: int): """Look down continuously at speed x"""; mouse_move_continuous(0, 1, speed)
    def game_look_down_continuous_5(): """Look down continuously speed 5"""; mouse_move_continuous(0, 1, 5)
    def game_look_down_continuous_10(): """Look down continuously speed 10"""; mouse_move_continuous(0, 1, 10)
    def game_look_down_continuous_20(): """Look down continuously speed 20"""; mouse_move_continuous(0, 1, 20)
    def game_look_down_continuous_30(): """Look down continuously speed 30"""; mouse_move_continuous(0, 1, 30)
    def game_look_down_continuous_50(): """Look down continuously speed 50"""; mouse_move_continuous(0, 1, 50)
    def game_look_down_continuous_100(): """Look down continuously speed 100"""; mouse_move_continuous(0, 1, 100)
    def game_turn_continuous_stop(): """Stop turning left continuously"""; mouse_move_continuous_stop(150)
    def game_turn_180(): """Turn 180"""; mouse_move_degrees(180, 0, action_duration_ms)
    def game_turn_360(): """Turn 360"""; mouse_move_degrees(360, 0, 1500)
    def game_look_up_15(): """Look up 15 degrees"""; mouse_move_degrees(0, -15, action_duration_ms)
    def game_look_up_30(): """Look up 30 degrees"""; mouse_move_degrees(0, -30, action_duration_ms)
    def game_look_up_45(): """Look up 45 degrees"""; mouse_move_degrees(0, -45, action_duration_ms)
    def game_look_up_60(): """Look up 60 degrees"""; mouse_move_degrees(0, -60, action_duration_ms)
    def game_look_up_75(): """Look up 75 degrees"""; mouse_move_degrees(0, -75, action_duration_ms)
    def game_look_up_90(): """Look up 90 degrees"""; mouse_move_degrees(0, -90, action_duration_ms)
    def game_look_up(deg: int): """Look up y degrees"""; mouse_move_degrees(0, -deg, action_duration_ms)
    def game_look_down_15(): """Look down 15 degrees"""; mouse_move_degrees(0, 15, action_duration_ms)
    def game_look_down_30(): """Look down 30 degrees"""; mouse_move_degrees(0, 30, action_duration_ms)
    def game_look_down_45(): """Look down 45 degrees"""; mouse_move_degrees(0, 45, action_duration_ms)
    def game_look_down_60(): """Look down 60 degrees"""; mouse_move_degrees(0, 60, action_duration_ms)
    def game_look_down_75(): """Look down 75 degrees"""; mouse_move_degrees(0, 75, action_duration_ms)
    def game_look_down_90(): """Look down 90 degrees"""; mouse_move_degrees(0, 90, action_duration_ms)
    def game_look_down(deg: int): """Look down y degrees"""; mouse_move_degrees(0, deg, action_duration_ms)
    def game_reset_center_y(): """Reset the mouse to the center of the screen"""; mouse_reset_center_y()
    def game_calibrate_x_360(num: int): """Calibrate the mouse for x movement in degrees"""; mouse_calibrate_x_360(num)
    def game_calibrate_y_90(num: int): """Calibrate the mouse for y movement in degrees"""; mouse_calibrate_90_y(num)